### ISSUE TITLE
Query about passing environment variables

### ISSUE THREAD

**Issue by kuldeepsidhu88** [craig-rueda/tomcat-native-spring-boot-sample#1]
I am able to run the application as it is. 
I am bit confused about how variables **SERVER_SSL_CERTIFICATEKEYFILE** and **SERVER_SSL_CERTIFICATEFILE** in Dockerfile are being used in application.

If I dont pass them in docker file, the application wont work even if I give the path properly in **application.properties** file. It fails with error file not found exception.

I am not able to understand how these SSL variables are being read when in code its asking for different environment variables

```java
certificateFile = applicationContext.getEnvironment().getProperty("server.ssl.certificateFile");
certificateKeyFile = applicationContext.getEnvironment().getProperty("server.ssl.certificateKeyFile");
```

Can you please help me in understanding the full context.
And how to redirect non-secure requests to secure port automatically? Do I need to add new Connector to tomcat config for that ? I tried to set the redirection in same connection but it was not working.

**Comment by kuldeepsidhu88** [comment]
@craig-rueda Can you please help with above queries.

**Comment by craig-rueda** [comment]
I'm using the built in Spring configuration which converts env vars into config keys on the environment. As far as redirects are concerned, I would do that in nginx, or you could also create another webserver context in spring that listens on 80 and defines a few redirect rules.

**Comment by kuldeepsidhu88** [comment]
Thanks for the reply. I am able to redirect to secure port. But still I am confused. I cannot see any additional libraries in pom.xml. How **SERVER_SSL_CERTIFICATEFILE** is being translated to **server.ssl.certificateFile** and so on.
